name: Start Work
on: workflow_dispatch
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GM Actions!
      - name: Print few lines
        run: |
          echo First line!
          echo Second line!
  
